from PyQt5.QtWidgets import (
    QWidget, QVBoxLayout, QHBoxLayout, QLabel, QPushButton, QSizePolicy
)

from PyQt5.QtCore import Qt
from utilities.merger_ui_widgets import MergerUIWidgetsMixin

class MergerUIBuildMixin(MergerUIWidgetsMixin):
    def setup_ui(self):
        root = QWidget(self.parent)
        root.setObjectName("centralWidget")
        self.parent.setCentralWidget(root)
        outer = QVBoxLayout(root)
        outer.setContentsMargins(40, 15, 40, 15)
        outer.setSpacing(8)
        title = QLabel('Arrange Videos in the Desired Order')
        title.setObjectName("titleLabel")
        title.setStyleSheet("font-size: 18px; font-weight: bold; color: #7DD3FC;")
        title.setAlignment(Qt.AlignHCenter)
        title.setSizePolicy(QSizePolicy.Preferred, QSizePolicy.Fixed)
        outer.addWidget(title)
        list_container = QHBoxLayout()
        list_container.setSpacing(12)
        outer.addLayout(list_container, 1)
        self.parent.listw = self.parent.create_draggable_list_widget()
        self.parent.listw.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        list_container.addWidget(self.parent.listw, 1)
        move_buttons_layout = self.create_move_buttons()
        list_container.addLayout(move_buttons_layout, 0)
        bottom_band = self.create_bottom_band()
        merge_row = self.create_merge_row()
        action_buttons_row = QHBoxLayout()
        action_buttons_row.setContentsMargins(0, 0, 0, 0)
        action_buttons_row.addWidget(self.parent.btn_undo)
        action_buttons_row.addSpacing(10)
        action_buttons_row.addWidget(self.parent.btn_redo)
        action_buttons_row.addStretch(1)
        action_buttons_row.addWidget(self.parent.btn_add)
        action_buttons_row.addSpacing(20)
        action_buttons_row.addWidget(self.parent.btn_add_folder)
        action_buttons_row.addStretch(1)
        action_buttons_row.addWidget(self.parent.btn_remove)
        action_buttons_row.addSpacing(14)
        action_buttons_row.addWidget(self.parent.btn_clear)
        action_buttons_row.addSpacing(80)
        outer.addLayout(action_buttons_row, 0)
        outer.addWidget(bottom_band, 0)
        self.parent.status_label = QLabel("Ready. Add 1 to 100 videos to begin.")
        self.parent.status_label.setStyleSheet("color: #7289da; font-weight: bold; font-size: 14px;")
        self.parent.status_label.setAlignment(Qt.AlignCenter)
        outer.addWidget(self.parent.status_label, 0)
        outer.addWidget(merge_row, 0)
        outer.addSpacing(35) # Leave room for the overlay progress bar at the very bottom

    def create_move_buttons(self):
        col = QVBoxLayout()
        col.setContentsMargins(0, 0, 0, 0)
        col.setSpacing(15)
        self.parent.btn_add = QPushButton("ADD VIDEOS")
        self.parent.btn_add.setObjectName("aux-btn")
        self.parent.btn_add.setFixedSize(120, 36)
        self.parent.btn_add.setCursor(Qt.PointingHandCursor)
        self.parent.btn_add_folder = QPushButton("ADD FOLDER")
        self.parent.btn_add_folder.setObjectName("aux-btn")
        self.parent.btn_add_folder.setFixedSize(120, 36)
        self.parent.btn_add_folder.setCursor(Qt.PointingHandCursor)
        self.parent.btn_remove = QPushButton("REMOVE SELECTED")
        self.parent.btn_remove.setObjectName("danger-btn")
        self.parent.btn_remove.setFixedSize(125, 36)
        self.parent.btn_remove.setCursor(Qt.PointingHandCursor)
        self.parent.btn_clear = QPushButton("CLEAR ALL")
        self.parent.btn_clear.setObjectName("danger-btn")
        self.parent.btn_clear.setFixedSize(125, 36)
        self.parent.btn_clear.setCursor(Qt.PointingHandCursor)
        self.parent.btn_up = QPushButton("▲")
        self.parent.btn_up.setObjectName("moveUpBtn")
        self.parent.btn_up.setToolTip("Move selected video up (Ctrl+Up)")
        self.parent.btn_up.setFixedSize(55, 50)
        self.parent.btn_up.setCursor(Qt.PointingHandCursor)
        self.parent.btn_up.clicked.connect(lambda: self.parent.move_item(-1))
        self.parent.btn_down = QPushButton("▼")
        self.parent.btn_down.setObjectName("moveDownBtn")
        self.parent.btn_down.setToolTip("Move selected video down (Ctrl+Down)")
        self.parent.btn_down.setFixedSize(55, 50)
        self.parent.btn_down.setCursor(Qt.PointingHandCursor)
        self.parent.btn_down.clicked.connect(lambda: self.parent.move_item(1))
        col.addStretch(1)
        col.addWidget(self.parent.btn_up, 0, Qt.AlignCenter)
        col.addWidget(self.parent.btn_down, 0, Qt.AlignCenter)
        col.addStretch(1)
        return col

    def create_bottom_band(self):
        band = QHBoxLayout()
        band.setContentsMargins(0, 0, 0, 0)
        left_wrap = QWidget()
        left_wrap.setLayout(self.create_music_layout())
        center_wrap = QWidget()
        center_wrap.setLayout(self.create_center_buttons())
        right_wrap = QWidget()
        right_wrap.setLayout(self.create_quality_column())
        band.addWidget(left_wrap, 0, Qt.AlignLeft)
        band.addStretch(1)
        band.addWidget(right_wrap, 0, Qt.AlignCenter)
        band.addStretch(1)
        band.addWidget(center_wrap, 0, Qt.AlignRight)
        wrap = QWidget()
        wrap.setLayout(band)
        return wrap