class UI_COLORS:
    BACKGROUND_DARK = "#111827"
    BACKGROUND_MEDIUM = "#1F2937"
    BACKGROUND_LIGHT = "#374151"
    TEXT_PRIMARY = "#F9FAFB"
    TEXT_SECONDARY = "#E5E7EB"
    TEXT_DISABLED = "#9CA3AF"
    TEXT_ACCENT = "#2563EB"
    TEXT_WARNING = "#FBBF24"
    TEXT_DANGER = "#FEE2E2"
    BORDER_DARK = "#374151"
    BORDER_MEDIUM = "#4B5563"
    BORDER_ACCENT = "#2563EB"
    BORDER_DANGER = "#991B1B"
    BUTTON_DEFAULT = "#374151"
    BUTTON_HOVER = "#4B5563"
    BUTTON_PRESSED = "#1F2937"
    BUTTON_DISABLED = "#6B7280"
    PRIMARY = "#2563EB"
    PRIMARY_HOVER = "#3B82F6"
    PRIMARY_PRESSED = "#1D4ED8"
    PRIMARY_BORDER = "#1E3A8A"
    SUCCESS = "#10B981"
    SUCCESS_HOVER = "#34D399"
    SUCCESS_PRESSED = "#059669"
    SUCCESS_BORDER = "#047857"
    WARNING = "#F59E0B"
    WARNING_HOVER = "#FBBF24"
    WARNING_PRESSED = "#D97706"
    WARNING_BORDER = "#92400E"
    DANGER = "#7F1D1D"
    DANGER_HOVER = "#991B1B"
    DANGER_PRESSED = "#5B0F0F"
    DANGER_BORDER = "#4C0519"
    ACCENT = "#0D9488"
    ACCENT_HOVER = "#14B8A6"
    ACCENT_PRESSED = "#0F766E"
    ACCENT_BORDER = "#0F766E"
    OVERLAY_DIM = "rgba(0, 0, 0, 120)"
    TRANSPARENT = "transparent"
    HANDLE_BLUE = "#3498db"
    HANDLE_ORANGE = "#e67e22"
    MARCHING_ANTS = "white"
    SELECTION_GREEN = "#10B981"
    OPACITY_DIM_HIGH = 180
    OPACITY_DIM_MED = 120
    OPACITY_DIM_LOW = 90
    OPACITY_PH_ALPHA = 80

class UI_LAYOUT:
    WIZARD_HEADER_HEIGHT = 130
    PROGRESS_BAR_HEIGHT = 25
    TIME_LABEL_WIDTH = 60
    BUTTON_HEIGHT = 32
    BUTTON_PADDING_H = "1px 10px"
    BUTTON_FONT_SIZE = "11px"
    BUTTON_BORDER_RADIUS = "3px"
    BUTTON_BORDER_BOTTOM_WIDTH = "3px"
    BUTTON_LARGE_PADDING_H = "2px 12px"
    BUTTON_LARGE_FONT_SIZE = "12px"
    SCROLLBAR_SIZE = "22px"
    SCROLLBAR_HANDLE_MIN_LENGTH = "40px"
    SCROLLBAR_BORDER_RADIUS = "8px"
    SCROLLBAR_HANDLE_BORDER = "2px"
    PORTRAIT_TOOLBAR_MARGINS = "5px"
    PORTRAIT_TOOLBAR_SPACING = "5px"
    PORTRAIT_TOOLBAR_BORDER_RADIUS = "8px"
    GRAPHICS_HANDLE_SIZE = 25
    GRAPHICS_TEXT_PADDING = 40
    GRAPHICS_TEXT_HEIGHT_PAD = 10
    GRAPHICS_TEXT_FONT_SIZE = 28
    GRAPHICS_TEXT_OFFSET_Y = 15
    GRAPHICS_ITEM_MIN_SIZE = 20
    PORTRAIT_TOP_BAR_HEIGHT = 150
    PORTRAIT_BASE_WIDTH = 1080
    PORTRAIT_BASE_HEIGHT = 1920
    PORTRAIT_BOTTOM_PADDING = 150
    PORTRAIT_CONTENT_HEIGHT = 1620
    ROLE_TOOLBAR_PADDING = 16
    ROLE_TOOLBAR_OFFSET = 12
    ROLE_TOOLBAR_EDGE_MARGIN = 8

class UI_BEHAVIOR:
    SNAP_THRESHOLD = 15
    SNAP_SMOOTHING_ALPHA = 0.8
    SNAP_RESIZE_SMOOTHING_ALPHA = 0.45
    SNAP_CENTER_THRESHOLD = 80
    SNAP_GUIDE_THRESHOLD = 95
    SNAP_CENTER_LOCK_THRESHOLD = 60
    SNAP_REPEAT_SUPPRESS_COUNT = 8
    ANT_DASH_PATTERN = "6, 6"
    ANT_DASH_INTERVAL = 100
    MAGNIFIER_SIZE = 180
    MAGNIFIER_ZOOM = 3.0
    MAGNIFIER_OFFSET = 60
    MAGNIFIER_CURSOR_CROSS_SIZE = 10
    MAGNIFIER_BORDER_WIDTH = 3
    MAGNIFIER_BORDER_COLOR = "#00FF00"
    MAGNIFIER_CROSS_COLOR = "red"
    SNAPSHOT_RETRY_INTERVAL_MS = 100
    SNAPSHOT_MAX_RETRIES = 20
    SLIDER_UPDATE_INTERVAL_MS = 100
    VIDEO_VIEW_GUIDANCE_BLINK_INTERVAL = 700
    MAGIC_WAND_MAX_SECONDS = 8
    MAGIC_WAND_PREVIEW_DELAY_MS = 450
    UNDO_COALESCE_WINDOW_MS = 400
    SELECTION_MIN_SIZE = 10
    KEYBOARD_NUDGE_STEP = 2.0
    ANT_DASH_PATTERN = "4, 4"
HUD_ELEMENT_MAPPINGS = {
    "loot": "Loot Area",
    "stats": "Mini Map + Stats",
    "normal_hp": "Own Health Bar (HP)",
    "boss_hp": "Boss HP (For When You Are The Boss Character)",
    "team": "Teammates health Bars (HP)",
    "spectating": "Spectating Eye"
}
HUD_ELEMENT_KEYS_BY_NAME = {v: k for k, v in HUD_ELEMENT_MAPPINGS.items()}
Z_ORDER_MAP = {
    'main': 0,
    'loot': 10,
    'normal_hp': 20,
    'boss_hp': 20,
    'stats': 30,
    'team': 40,
    'spectating': 100
}
