<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\FortniteVideoSoftware.Core\FortniteVideoSoftware.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" Version="11.0.10" />
    <PackageReference Include="Avalonia.Diagnostics" Version="11.0.10" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.0.10" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.0.10" />
    <PackageReference Include="Avalonia.Controls.ColorPicker" Version="11.0.10" />
    <PackageReference Include="Avalonia.Controls.DataGrid" Version="11.0.10" />
    <PackageReference Include="System.Windows.Extensions" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="payload.zip" Condition="Exists('payload.zip')" />
    <TrimmerRootAssembly Include="Avalonia.Controls.ColorPicker" />
    <TrimmerRootAssembly Include="Avalonia.Controls.DataGrid" />
    <TrimmerRootAssembly Include="Avalonia.Themes.Fluent" />
    <TrimmerRootAssembly Include="SkiaSharp" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishAot>true</PublishAot>
    <InvariantGlobalization>false</InvariantGlobalization>
    <TrimMode>full</TrimMode>
    <SuppressTrimAnalysisWarnings>true</SuppressTrimAnalysisWarnings>
    <SuppressAotAnalysisWarnings>true</SuppressAotAnalysisWarnings>
    <IlcTrimMetadata>false</IlcTrimMetadata>
    <ApplicationIcon>..\..\assets\icons\Video_Icon_File.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

</Project>
