from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QWidget, QVBoxLayout, QLabel, QHBoxLayout, QSlider
from ui.widgets.music_wizard_style import MergerUIStyle
from ui.widgets.music_wizard_timeline_widget import MergerTimelineWidget

class MergerMusicWizardStep3PageMixin:
    def setup_step3_timeline(self):
        page = QWidget()
        layout = QVBoxLayout(page)
        layout.setSpacing(0)
        layout.setContentsMargins(0, 0, 0, 0)
        layout.addSpacing(10)
        self.lbl_step3 = QLabel("STEP 3: Preview Project Timeline")
        self.lbl_step3.setStyleSheet("font-size: 20px; font-weight: bold; color: #7DD3FC; padding: 0px; margin: 0px;")
        self.lbl_step3.setAlignment(Qt.AlignCenter)
        self.lbl_step3.setFixedHeight(30)
        layout.addWidget(self.lbl_step3)
        layout.addSpacing(10)
        player_volume_row = QHBoxLayout()
        player_volume_row.setSpacing(15)
        self.video_container = QWidget()
        self.video_container.setMinimumHeight(350)
        self.video_container.setStyleSheet("background: #000; border: 2px solid #34495e;")
        self.video_container.setAttribute(Qt.WA_DontCreateNativeAncestors)
        self.video_container.setAttribute(Qt.WA_NativeWindow)
        self.video_container.setAttribute(Qt.WA_OpaquePaintEvent)
        self.video_container.setAttribute(Qt.WA_NoSystemBackground)
        player_volume_row.addWidget(self.video_container, 1)
        self.video_container.winId()
        vol_col = QVBoxLayout()
        vol_col.setSpacing(10)
        vol_col.setContentsMargins(10, 0, 10, 0)
        vol_labels = QHBoxLayout()
        v_l = QLabel("VIDEO"); v_l.setStyleSheet("font-size: 10px; font-weight: bold; color: #7DD3FC;"); v_l.setAlignment(Qt.AlignCenter)
        m_l = QLabel("MUSIC"); m_l.setStyleSheet("font-size: 10px; font-weight: bold; color: #7DD3FC;"); m_l.setAlignment(Qt.AlignCenter)
        vol_labels.addWidget(v_l); vol_labels.addSpacing(30); vol_labels.addWidget(m_l)
        vol_col.addLayout(vol_labels)
        vol_sliders = QHBoxLayout()
        vol_sliders.setSpacing(30)
        self.video_vol_slider = QSlider(Qt.Vertical)
        self.video_vol_slider.setRange(0, 100); self.video_vol_slider.setValue(100); self.video_vol_slider.setFixedWidth(40)
        self.video_vol_slider.setStyleSheet(MergerUIStyle.SLIDER_VOLUME_VERTICAL_METALLIC)
        self.video_vol_slider.setCursor(Qt.PointingHandCursor)
        self.video_vol_slider.valueChanged.connect(self._on_video_vol_changed)
        self.music_vol_slider = QSlider(Qt.Vertical)
        self.music_vol_slider.setRange(0, 100); self.music_vol_slider.setValue(80); self.music_vol_slider.setFixedWidth(40)
        self.music_vol_slider.setStyleSheet(MergerUIStyle.SLIDER_MUSIC_VERTICAL_METALLIC)
        self.music_vol_slider.setCursor(Qt.PointingHandCursor)
        self.music_vol_slider.valueChanged.connect(self._on_music_vol_changed)
        vol_sliders.addWidget(self.video_vol_slider); vol_sliders.addWidget(self.music_vol_slider)
        vol_col.addLayout(vol_sliders)
        val_labels = QHBoxLayout()
        val_labels.setSpacing(30)
        self.video_vol_val_lbl = QLabel("100%"); self.video_vol_val_lbl.setStyleSheet("font-size: 11px; font-weight: bold; color: white;"); self.video_vol_val_lbl.setAlignment(Qt.AlignCenter)
        self.music_vol_val_lbl = QLabel("80%"); self.music_vol_val_lbl.setStyleSheet("font-size: 11px; font-weight: bold; color: white;"); self.music_vol_val_lbl.setAlignment(Qt.AlignCenter)
        val_labels.addWidget(self.video_vol_val_lbl, 0, Qt.AlignCenter); val_labels.addWidget(self.music_vol_val_lbl, 0, Qt.AlignCenter)
        vol_col.addLayout(val_labels)
        player_volume_row.addLayout(vol_col)
        layout.addLayout(player_volume_row, 10)
        layout.addSpacing(10)
        self.timeline_container = QWidget()
        self.timeline_container.setMinimumHeight(100)
        container_layout = QVBoxLayout(self.timeline_container)
        container_layout.setContentsMargins(0,0,0,0)
        self.timeline = MergerTimelineWidget(self)
        self.timeline.clicked_pos.connect(self._on_timeline_seek)
        container_layout.addWidget(self.timeline)
        self.splash_overlay = QWidget(self.timeline_container)
        self.splash_overlay.setStyleSheet("background: rgba(15, 25, 35, 240); border-radius: 8px;")
        splash_layout = QVBoxLayout(self.splash_overlay)
        self.splash_lbl = QLabel("?  PREPARING HIGH-DENSITY TIMELINE...  ?")
        self.splash_lbl.setStyleSheet("color: #7DD3FC; font-size: 18px; font-weight: bold;")
        self.splash_lbl.setAlignment(Qt.AlignCenter)
        splash_layout.addWidget(self.splash_lbl)
        self.splash_overlay.hide()
        layout.addWidget(self.timeline_container, 1)
        layout.addStretch(0)
        self.stack.addWidget(page)
